changelog:
  exclude:
    labels:
      - 'ignore-for-release'
      - 'dependencies'
  categories:
    - title: '🚀 Features'
      labels:
        - 'enhancement'
        - 'feature'
    - title: '🐛 Bug Fixes'
      labels:
        - 'bug'
        - 'bugfix'
    - title: '📚 Documentation'
      labels:
        - 'documentation'
        - 'docs'
    - title: '🧪 Tests'
      labels:
        - 'tests'
        - 'testing'
    - title: '🔧 Maintenance'
      labels:
        - 'maintenance'
        - 'refactor'
        - 'ci'
    - title: '⬆️ Dependencies'
      labels:
        - 'dependencies'
    - title: '🔄 Other Changes'
      labels:
        - '*'
