name: Benchmarks

on:
  pull_request:
    branches: [ main ]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Important for asv to access the git history

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.12"
        enable-cache: true

    - name: Install dependencies
      run: |
        uv pip install 'asv<0.6.2' virtualenv
        uv pip install "."

    - name: Run benchmarks
      run: |
        cd benchmarks
        asv machine --yes
        asv run HEAD^..HEAD
        asv compare HEAD^ HEAD --factor 1.1 --split > benchmark_results.txt

    - name: Comment PR with benchmark results
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const results = fs.readFileSync('benchmark_results.txt', 'utf8');
          const comment = `### Benchmark Results\n\n\`\`\`\n${results}\n\`\`\``;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.name,
            body: comment
          });
